import { type Database } from "./supabase.types";

import {
  Utensils,
  HomeIcon,
  Car,
  Heart,
  Briefcase,
  ReceiptText,
  ShoppingCart,
  Plane,
  Zap,
  BookOpen,
  Settings,
  Palette,
  Dog,
  Gamepad,
  Hospital,
  Gift,
  HandCoins,
  Pill,
  Monitor,
  Pizza,
  Volleyball,
  Drama,
  Package,
  PiggyBank,
  Handshake,
  Motorbike,
  Baby,
  Hamburger,
  Beer,
  ShoppingBag,
  Shirt,
  ShoppingBasket,
} from "lucide-react";

export const ICON_OPTIONS = [
  { name: "Utensils", Component: Utensils },
  { name: "Home", Component: HomeIcon },
  { name: "Car", Component: Car },
  { name: "Heart", Component: Heart },
  { name: "Briefcase", Component: Briefcase },
  { name: "ReceiptText", Component: ReceiptText },
  { name: "ShoppingCart", Component: ShoppingCart },
  { name: "Plane", Component: Plane },
  { name: "Zap", Component: Zap },
  { name: "BookOpen", Component: BookOpen },
  { name: "Settings", Component: Settings },
  { name: "Palette", Component: Palette },
  { name: "Dog", Component: Dog },
  { name: "Gamepad", Component: Gamepad },
  { name: "Hospital", Component: Hospital },
  { name: "Gift", Component: Gift },
  { name: "HandCoins", Component: HandCoins },
  { name: "Pill", Component: Pill },
  { name: "Monitor", Component: Monitor },
  { name: "Pizza", Component: Pizza },
  { name: "Volleyball", Component: Volleyball },
  { name: "Drama", Component: Drama },
  { name: "Package", Component: Package },
  { name: "PiggyBank", Component: PiggyBank },
  { name: "Handshake", Component: Handshake },
  { name: "Motorbike", Component: Motorbike },
  { name: "Baby", Component: Baby },
  { name: "Hamburger", Component: Hamburger },
  { name: "Beer", Component: Beer },
  { name: "ShoppingBag", Component: ShoppingBag },
  { name: "ShoppingBasket", Component: ShoppingBasket },
  { name: "Shirt", Component: Shirt },
];

export type CategoryType = "income" | "expense";

export type DbCategory = Database["public"]["Tables"]["categories"]["Row"];
export type InsertCategory = Database["public"]["Tables"]["categories"]["Insert"];
